=== Poeticode/LazyBars/_src/js/app/schema/poetry.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "partialsName": {
        "type": "string"
      },
      "slug": {
        "type": "string"
      },
      "dest": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "html_content": {
        "type": "string"
      },
      "content": {
        "type": "string"
      },
      "author_notes": {
        "type": "string"
      }
    },
    "required": [
      "partialsName",
      "slug",
      "dest",
      "title",
      "html_content",
      "content",
      "author_notes"
    ]
  }
}

=== Poeticode/LazyBars/_src/hbs/data/dynamic/poetry.json
[{
    "partialsName": "poem",
    "slug": "silent_silas",
    "dest": "poetry/",
    "title": "Silent Silas",
    "html_content": "The windows to my soul<br />Tend to have their blinds up,<br />And I leave the door locked tight<br />By keeping my own mouth shut<br /><br />So my apologies if it's frustrating<br />That I'm so cold and calculating.<br />It's my modus operandi;<br />You can't spell 'Silent' without Si.<br /><br />But if it's any consolation,<br />I am striving to get better<br />At voicing my own thoughts<br />Without resorting to writing letters.",
    "content": "The windows to my soul\\nTend to have their blinds up,\\nAnd I leave the door locked tight\\nBy keeping my own mouth shut\\n\\nSo my apologies if it's frustrating\\nThat I'm so cold and calculating.\\nIt's my modus operandi;\\nYou can't spell 'Silent' without Si.\\n\\nBut if it's any consolation,\\nI am striving to get better\\nAt voicing my own thoughts\\nWithout resorting to writing letters.",
    "author_notes": "a lil quick lil ditty"
}, {"partialsName":"poem",
    "slug":"breakfast_blues_pt1",
    "dest":"poetry/",
    "title":"Breakfast Blues",
    "html_content":"Lost my reason to wake in the morning<br> Ever since you left me without warning.<br> We've always seemed to have gotten along<br> Now I'm wondering if I did you wrong.<br> <br> Lost my reason to give you thanks and praise.<br> Each day that passes passes in a daze.<br> The life I live is a life of decay.<br> My happiness happens to never stay.<br> <br> I would have treated you so much better,<br> Or perhaps branded a scarlet letter<br> Across my chest and openly confess<br> That I'm impressed by a snack I love best.<br> <br> Oh chocolate muffin, why'd you have to leave?<br> I've learned not to wear my heart on my sleeve.<br> Instead my love will always be suppressed<br> As I keep it locked in a chocolate chest.",    "content":"Lost my reason to wake in the morning\\\\n Ever since you left me without warning.\\\\n We've always seemed to have gotten along\\\\n Now I'm wondering if I did you wrong.\\\\n \\\\n Lost my reason to give you thanks and praise.\\\\n Each day that passes passes in a daze.\\\\n The life I live is a life of decay.\\\\n My happiness happens to never stay.\\\\n \\\\n I would have treated you so much better,\\\\n Or perhaps branded a scarlet letter\\\\n Across my chest and openly confess\\\\n That I'm impressed by a snack I love best.\\\\n \\\\n Oh chocolate muffin, why'd you have to leave?\\\\n I've learned not to wear my heart on my sleeve.\\\\n Instead my love will always be suppressed\\\\n As I keep it locked in a chocolate chest.",
    "author_notes":"a lil quick lil ditty"},
    {"partialsName":"poem","slug":"breakfast_blues_pt_ii","dest":"poetry/","title":"Breakfast Blues Pt. 2","html_content":"Oh, my good friend, I didn't mean to leave.<br> It wasn't your fault, so no longer grieve!<br> If I could, I would run back to your side.<br> But, alas, a lack of legs slows my stride.<br> <br> It's been over a year since I've last seen<br> Your serious face and Chartwell's cuisine.<br> Often I think this is for the better<br> 'Til I shed tears as I read your letter.<br> <br> Fake tears, that is, for I also lack eyes.<br> In fact, let me unveil my disguise:<br> I'm an object lacking animation,<br> Given life through personification.<br> <br> What words can I say to help you move on<br> And accept the fact that I am now gone?<br> Know that I too will miss your sweet lovin'<br> For I'll always be your chocolate muffin.","content":"Oh, my good friend, I didn't mean to leave.<br> It wasn't your fault, so no longer grieve!<br> If I could, I would run back to your side.<br> But, alas, a lack of legs slows my stride.<br> <br> It's been over a year since I've last seen<br> Your serious face and Chartwell's cuisine.<br> Often I think this is for the better<br> 'Til I shed tears as I read your letter.<br> <br> Fake tears, that is, for I also lack eyes.<br> In fact, let me unveil my disguise:<br> I'm an object lacking animation,<br> Given life through personification.<br> <br> What words can I say to help you move on<br> And accept the fact that I am now gone?<br> Know that I too will miss your sweet lovin'<br> For I'll always be your chocolate muffin.","author_notes":"a lil quick lil ditty"},
    {"partialsName":"poem","slug":"wake_n_bake","dest":"poetry/","title":"Wake N Bake","html_content":"I tried out the Wake n' Bake<br> To shake up<br> My destined Fate <br> For curiosity's sake.<br> <br> But these tracks of Time,<br> Which I could finally find,<br> Simultaneously found <br> To no longer be mine,<br> <br> Led me down the wrong course<br> To a destination my Fate<br> Never quite had in mind,<br> <br> But with the Lord's hand in mine,<br> Instead of being my Guide,<br> He played a magic trick.<br> (Which is when you manage to hide<br> <br> Material manipulations<br> From the crowd's<br> Ever watchful eyes)<br> <br> So to my surprise, <br> between our clasped hands,<br> The Lord changed the decision<br> Of one of my Life's plans<br> To give me the upperhand.<br> <br> \"Class is cancelled.\"<br> I stopped reading after that,<br> <br> Because, to be Frank,<br> (Like, from It's Always Sunny)<br> I no longer gave a fuck<br> <br> And instead gave my thanks <br> to the Stroke of Luck.<br> <br> \"What a misfortunate name!\"<br> I had laughed to myself.<br> \"Shit, who am I talking to?\"<br> <br> And, once again, <br> The Lord hid himself.","content":"I tried out the Wake n' Bake<br> To shake up<br> My destined Fate <br> For curiosity's sake.<br> <br> But these tracks of Time,<br> Which I could finally find,<br> Simultaneously found <br> To no longer be mine,<br> <br> Led me down the wrong course<br> To a destination my Fate<br> Never quite had in mind,<br> <br> But with the Lord's hand in mine,<br> Instead of being my Guide,<br> He played a magic trick.<br> (Which is when you manage to hide<br> <br> Material manipulations<br> From the crowd's<br> Ever watchful eyes)<br> <br> So to my surprise, <br> between our clasped hands,<br> The Lord changed the decision<br> Of one of my Life's plans<br> To give me the upperhand.<br> <br> \"Class is cancelled.\"<br> I stopped reading after that,<br> <br> Because, to be Frank,<br> (Like, from It's Always Sunny)<br> I no longer gave a fuck<br> <br> And instead gave my thanks <br> to the Stroke of Luck.<br> <br> \"What a misfortunate name!\"<br> I had laughed to myself.<br> \"Shit, who am I talking to?\"<br> <br> And, once again, <br> The Lord hid himself.","author_notes":"a lil quick lil ditty"},
    {"partialsName":"poem","slug":"haiku_4","dest":"poetry/","title":"Haiku #4","html_content":"I wish I could draw.<br> Picture's worth a thousand words;<br> This has just fourteen.","content":"I wish I could draw.<br> Picture's worth a thousand words;<br> This has just fourteen.","author_notes":"a lil quick lil ditty"},
    {"partialsName":"poem","slug":"leafblower","dest":"poetry/","title":"Leafblower","html_content":"You're the girl sitting on the park bench.<br> I'm the guy with a leaf blower.<br> I've gotta do my job,<br> So would you kindly please move over?<br> <br> I'm walking right towards you,<br> So don't say you didn't notice me.<br> I'd like to get off work soon,<br> So I'll give you until the count of three.<br> <br> One<br> Two<br> ...<br> <br> Alright, so you've called my bluff.<br> I'm not really going to do anything.<br> I just wanted to look real tough,<br> But this little bee ain't got no sting.<br> <br> I'll just tell my boss that I missed a spot,<br> And I'll explain my sad situation.<br> Then we'll both laugh at the thought<br> Of me writing poetry about my frustration.","content":"You're the girl sitting on the park bench.<br> I'm the guy with a leaf blower.<br> I've gotta do my job,<br> So would you kindly please move over?<br> <br> I'm walking right towards you,<br> So don't say you didn't notice me.<br> I'd like to get off work soon,<br> So I'll give you until the count of three.<br> <br> One<br> Two<br> ...<br> <br> Alright, so you've called my bluff.<br> I'm not really going to do anything.<br> I just wanted to look real tough,<br> But this little bee ain't got no sting.<br> <br> I'll just tell my boss that I missed a spot,<br> And I'll explain my sad situation.<br> Then we'll both laugh at the thought<br> Of me writing poetry about my frustration.","author_notes":"a lil quick lil ditty"},
    {"partialsName":"poem","slug":"the_drinking_game","dest":"poetry/","title":"The Drinking Game","html_content":"I walk a thin line.<br> Every sip risks a stumble.<br> I play mind poker<br> With memory chips to fumble.<br> <br> I walk a thin line.<br> I let out a silent chuckle.<br> I sip from a glass<br> Gripped with a white knuckle.<br> <br> I walk a thin line.<br> The pot's full of promise.<br> I had raised my bet<br> With a hand most novice.<br> <br> I walk a thin line<br> With confidence unshaken.<br> I down my last glass<br> To dance with the mass,<br> Yet the couch I awaken.<br> <br> My memory chips were taken.<br> I walk a thin line.","content":"I walk a thin line.<br> Every sip risks a stumble.<br> I play mind poker<br> With memory chips to fumble.<br> <br> I walk a thin line.<br> I let out a silent chuckle.<br> I sip from a glass<br> Gripped with a white knuckle.<br> <br> I walk a thin line.<br> The pot's full of promise.<br> I had raised my bet<br> With a hand most novice.<br> <br> I walk a thin line<br> With confidence unshaken.<br> I down my last glass<br> To dance with the mass,<br> Yet the couch I awaken.<br> <br> My memory chips were taken.<br> I walk a thin line.","author_notes":"a lil quick lil ditty"},
